- name: Instalando HTTPs para apt.
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - nfs-common
    - git
    - vim
    - nano
    - acl
    - apparmor
    - net-tools

- name: Mudando TimeZone Para São Paulo Brasil
  timezone:
    name: America/Sao_Paulo

- name: Garantindo /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ipaddress }} {{ item.hostname }}"
  loop: "{{ k8s_machines }}"
