- name: Preprar o usuario root para executar o kubectl
  include_tasks: set-config.yaml

- name: Instala o MetalLB
  shell: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests/metallb-native.yaml

- name: Aguarda o MetalLB estar pronto
  shell: kubectl wait --for=condition=available --timeout=600s deployment -l app=metallb -n metallb-system
  register: result
  until: result.rc == 0
  retries: 60
  delay: 10

- name: Configura o MetalLB
  copy:
    dest: metallb-config.yaml
    content: |
      ---
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: first-pool
        namespace: metallb-system
      spec:
        addresses:
        - {{ metallb_range }}
      ---
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: advertisement
        namespace: metallb-system
      spec:
        ipAddressPools:
        - first-pool

- name: Aplica a configuração do MetalLB
  shell: kubectl apply -f metallb-config.yaml
