- name: Remove swap do arquivo /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
  - swap
  - none

- name: Desativa o swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Encaminhando o IPv4 e permitindo que o iptables veja o tráfego em ponte
  lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: '{{ item }}'
    state: present
    create: yes
  with_items:
  - 'overlay'
  - 'br_netfilter'

- name: modprobe
  command: '{{ item }}'
  with_items:
  - 'modprobe br_netfilter'
  - 'modprobe overlay'

- name: Encaminhando o IPv4 e permitindo que o iptables veja o tráfego em ponte
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: '{{ item }}'
    state: present
    create: yes
  with_items:
  - 'net.bridge.bridge-nf-call-iptables   = 1'
  - 'net.bridge.bridge-nf-call-ip6tables  = 1'
  - 'net.ipv4.ip_forward                  = 1'

- name: update sysctl
  command: sysctl --system

- name: Adicionando chave de assinatura GPG do Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Adiciona repositorio apt para versao estavel
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Instalando o containerd runtime e suas dependencias
  apt:
    name: containerd.io
    state: present
    update_cache: yes
  notify: restart containerd

- name: Verificar se o arquivo existe
  stat:
    path: /etc/containerd/config.toml
  register: file_stat

- name: Apagar o arquivo
  file:
    path: /etc/containerd/config.toml
    state: absent
  when: file_stat.stat.exists

- name: restart containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes

- name: Adiciona uma chave de assinatura apt para o Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adiciona repositorio apt para Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Instala os pacotes do Kubernetes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl
  notify: restart kubelet

- name: Marcando pacotes do k8s como não atualizáveis(hold)
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
  - kubelet
  - kubeadm
  - kubectl

- name: Verifica se join-command.sh existe
  stat:
    path: /tmp/join-command.sh
  register: join_command_stat

- name: Copia e renomeia o join-command
  copy:
    src: files/join-command
    dest: /tmp/join-command.sh
    mode: 0777
  when: not join_command_stat.stat.exists

- name: Add node to cluster
  command: sh /tmp/join-command.sh
  when: not join_command_stat.stat.exists

